version: '3'
services:
    app:
        build: .
        image: himmussel/larodon
        container_name: larodon-app
        restart: always
        networks:
          - backend
        ports:
          - 80:80
        depends_on: 
          - db
        volumes: 
          - "./.env:/var/www/.env"
          - "./application:/var/www"


    db:
        image: mysql:5.7
        container_name: laraveldb
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
          - backend
        volumes:
          - ./.docker/data:/var/lib/mysql
networks:
    backend:
        driver: bridge


